#!/usr/bin/env bash
# This script displays Best School 10 times and says "Hi" on the 9th iteration

count=1
while [ $count -le 10 ]; do
    if [ $count -eq 8 ]; then
        echo "Hi"
    else
        echo "Best School"
    fi
    ((count++))
done
